import type { Project } from '@/types';

export const PROJECTS: Project[] = [
  {
    id: 'lexora',
    title: 'LEXORA',
    tagline: 'Master New Languages with Joy: A Gamified Path to Fluency.',
    description: 'A language learning app with gamification, progress tracking, and modern learning flow.',
    fullDescription:
      'LEXORA is a modern language learning platform that combines academic curriculum effectiveness with addictive gamification elements. Designed to keep users motivated through intuitive progress tracking, a clean interface, and a naturally flowing learning path.',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    techDetails: [
      { name: 'Next.js', description: 'Core framework for optimal performance and SEO.' },
      { name: 'TypeScript', description: 'Ensures code safety and long-term scalability.' },
      { name: 'Tailwind CSS', description: 'Provides flexibility for modern and responsive UI design.' },
      { name: 'Framer Motion', description: 'Enlivens the application with smooth transition animations.' },
    ],
    features: [
      { title: 'Gamified Experience', detail: 'XP and Leveling system for learning motivation.' },
      { title: 'Progress Tracking', detail: 'Visualization of daily statistics and vocabulary mastery.' },
      { title: 'Modern Learning Flow', detail: 'Structured and easy-to-follow material flow.' },
      { title: 'Interactive Exercises', detail: 'Interactive exercises with real-time feedback.' },
      { title: 'Fully Responsive', detail: 'Learn comfortably on any device, anytime.' },
    ],
    image: '',
    link: 'https://github.com',
    featured: true,
  },
  {
    id: 'project-2',
    title: 'Coming Soon',
    tagline: 'Next project in progress.',
    description: 'A new project is currently in development. Stay tuned for updates.',
    fullDescription: 'This project is currently under development and will be available soon.',
    tech: ['Next.js', 'TypeScript'],
    techDetails: [],
    features: [],
    image: '',
    link: 'https://github.com/KevinKautsarr',
    featured: false,
  },
  {
    id: 'project-3',
    title: 'Coming Soon',
    tagline: 'Next project in progress.',
    description: 'A new project is currently in development. Stay tuned for updates.',
    fullDescription: 'This project is currently under development and will be available soon.',
    tech: ['React', 'Node.js'],
    techDetails: [],
    features: [],
    image: '',
    link: 'https://github.com/KevinKautsarr',
    featured: false,
  },
  {
    id: 'project-4',
    title: 'Coming Soon',
    tagline: 'Next project in progress.',
    description: 'A new project is currently in development. Stay tuned for updates.',
    fullDescription: 'This project is currently under development and will be available soon.',
    tech: ['Next.js', 'Tailwind CSS'],
    techDetails: [],
    features: [],
    image: '',
    link: 'https://github.com/KevinKautsarr',
    featured: false,
  },
  {
    id: 'project-5',
    title: 'Coming Soon',
    tagline: 'Next project in progress.',
    description: 'A new project is currently in development. Stay tuned for updates.',
    fullDescription: 'This project is currently under development and will be available soon.',
    tech: ['TypeScript', 'Laravel'],
    techDetails: [],
    features: [],
    image: '',
    link: 'https://github.com/KevinKautsarr',
    featured: false,
  },
  {
    id: 'project-6',
    title: 'Coming Soon',
    tagline: 'Next project in progress.',
    description: 'A new project is currently in development. Stay tuned for updates.',
    fullDescription: 'This project is currently under development and will be available soon.',
    tech: ['React Native', 'Firebase'],
    techDetails: [],
    features: [],
    image: '',
    link: 'https://github.com/KevinKautsarr',
    featured: false,
  },
];
